#!/usr/bin/env python3
"""Generate the per-module audio summaries (AI-generated speech) from the extracted syllabus text.

Engine: Piper TTS (MIT licence) with the en_US-ljspeech-medium voice (trained on the public-domain
LJ Speech dataset). Output: AAC/M4A, mono, 32 kbps, in web/content/audio/, plus
web/content/overlays/audio.json, which the app reads to show the player, size, duration, engine and
licence. Each file's text hash is stored, so unchanged modules are skipped on re-runs.

Usage:
  PIPER_BIN=/path/to/piper PIPER_MODEL=/path/to/en_US-ljspeech-medium.onnx python3 tools/build_audio.py [m0 m1 ...]
Requires ffmpeg on PATH.
"""
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODS = ROOT / "web" / "content" / "modules"
OUT = ROOT / "web" / "content" / "audio"
MANIFEST = ROOT / "web" / "content" / "overlays" / "audio.json"
PIPER = os.environ.get("PIPER_BIN", "piper")
MODEL = os.environ.get("PIPER_MODEL", "en_US-ljspeech-medium.onnx")


def speakable(text: str) -> str:
    """Mirror of web/js/tts.js speakable(): make symbols and currency readable aloud."""
    units = {"tn": "trillion", "bn": "billion", "m": "million"}
    t = re.sub(r"US\$\s?([\d,.]+)\s?(tn|trillion|bn|billion|m|million)?",
               lambda m: f"{m.group(1)} {units.get(m.group(2), m.group(2)) + ' ' if m.group(2) else ''}US dollars", text)
    t = re.sub(r"\bR\s?(\d[\d,.]*)\s?(billion|million|bn|m)?\b",
               lambda m: f"{m.group(1)} {units.get(m.group(2), m.group(2)) + ' ' if m.group(2) else ''}rand", t)
    t = re.sub(r"(\d)\s?bp\b", r"\1 basis points", t)
    for a, b in [("×", " times "), ("÷", " divided by "), ("−", " minus "), ("≈", " approximately "), ("→", ", then "),
                 ("≥", " at least "), ("≤", " at most "), ("±", " plus or minus "), ("^", " to the power "), ("√", " square root of "),
                 ("Σ", " sum of "), ("e.g.", "for example"), ("i.e.", "that is"), (" vs ", " versus ")]:
        t = t.replace(a, b)
    t = re.sub(r"\[(S|R|D)\d+\]", "", t)
    return re.sub(r"[ \t]+", " ", t).strip()


def duration(path: Path) -> float:
    out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=nk=1:nw=1", str(path)], capture_output=True, text=True)
    return float(out.stdout.strip() or 0)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    files = manifest.get("files", {})
    wanted = set(sys.argv[1:])
    for path in sorted(MODS.glob("m*.json"), key=lambda p: int(p.stem[1:])):
        mod = json.loads(path.read_text())
        if wanted and mod["id"] not in wanted:
            continue
        text = speakable(mod["audioSummary"]).replace("\n", "\n\n")
        digest = hashlib.sha256(text.encode()).hexdigest()[:12]
        target = OUT / f"{mod['id']}-summary.m4a"
        if files.get(mod["id"], {}).get("textHash") == digest and target.exists():
            print(f"{mod['code']}: unchanged")
            continue
        with tempfile.TemporaryDirectory() as tmp:
            wav = Path(tmp) / "out.wav"
            subprocess.run([PIPER, "-m", MODEL, "-f", str(wav), "--sentence_silence", "0.35"], input=text, text=True, check=True, capture_output=True)
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(wav), "-ac", "1", "-c:a", "aac", "-b:a", "32k",
                            "-metadata", f"title=GCM-101 {mod['code']} audio summary", "-metadata", "comment=AI-generated speech (Piper TTS, LJ Speech voice). Text from the GCM-101 syllabus.",
                            "-movflags", "+faststart", str(target)], check=True)
        files[mod["id"]] = {"file": target.name, "seconds": round(duration(target), 1), "bytes": target.stat().st_size, "textHash": digest}
        print(f"{mod['code']}: {files[mod['id']]['seconds']} s, {files[mod['id']]['bytes'] / 1024:.0f} KB")
    manifest = {
        "_about": "Generated by tools/build_audio.py — do not edit by hand. AI-generated speech; transcripts are the module audioSummary text.",
        "engine": {"name": "Piper TTS 1.2.0", "voice": "en_US-ljspeech-medium", "licence": "Piper is MIT-licensed; the voice was trained on the public-domain LJ Speech dataset", "aiGenerated": True},
        "files": files,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=1) + "\n")
    total = sum(f["bytes"] for f in files.values())
    print(f"{len(files)} files, {total / 1e6:.1f} MB total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
