#!/usr/bin/env node
// Writes web/sw-manifest.js: the list of app-shell files to precache and a version hash of their
// contents. Run after changing app code (npm run build). Content updates do not need this: the
// service worker revalidates course content on its own.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB = resolve(dirname(fileURLToPath(import.meta.url)), '../web');
const include = (rel) =>
  rel === 'index.html' || rel === 'manifest.webmanifest' ||
  /^(css|js|icons)\//.test(rel) ||
  /^content\/(course|glossary|about|audit)\.json$/.test(rel) ||
  /^content\/overlays\/[\w-]+\.json$/.test(rel);

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else {
      const rel = relative(WEB, p).split('\\').join('/');
      if (include(rel) && !name.startsWith('.')) files.push(rel);
    }
  }
})(WEB);
files.sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(WEB, f)));
const version = hash.digest('hex').slice(0, 10);
const shell = ['./', ...files];
const bytes = files.reduce((s, f) => s + statSync(join(WEB, f)).size, 0);
writeFileSync(join(WEB, 'sw-manifest.js'), `// Generated by tools/build-sw.mjs — do not edit.\nself.__GCM = ${JSON.stringify({ version, shell }, null, 1)};\n`);
console.log(`sw-manifest.js: ${files.length} files, ${(bytes / 1024).toFixed(0)} KB uncompressed, version ${version}`);
