#!/usr/bin/env node
// Versions the app so that a page never runs a mix of old and new code after a deploy.
//
// 1. Computes a version hash over the app shell (code, styles, icons, content index, overlays).
// 2. Rewrites the APP-MODULES block of index.html: an import map that maps every module
//    (js/x.js) to js/x.js?v=<version>, plus versioned modulepreload links and entry script.
//    Browsers, CDNs and the service worker cache by full URL, so a page that loaded version A
//    keeps requesting ?v=A, and a page that loaded version B requests ?v=B — never a mixture.
// 3. Puts the import map's SHA-256 hash in the Content-Security-Policy (index.html and _headers).
// 4. Writes sw-manifest.js: version + exact precache URLs.
//
// Usage: node tools/build-sw.mjs [webDir]   (run after any code or content change: npm run build)
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const WEB = resolve(process.argv[2] || join(dirname(fileURLToPath(import.meta.url)), '../web'));
const include = (rel) =>
  rel === 'manifest.webmanifest' ||
  /^(css|js|icons)\//.test(rel) ||
  /^content\/(course|glossary|about|audit)\.json$/.test(rel) ||
  /^content\/overlays\/[\w-]+\.json$/.test(rel);

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else {
      const rel = relative(WEB, p).split('\\').join('/');
      if (include(rel) && !name.startsWith('.')) files.push(rel);
    }
  }
})(WEB);
files.sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(WEB, f)));
// index.html counts too, minus the parts this script generates (so the hash is stable).
hash.update(readFileSync(join(WEB, 'index.html'), 'utf8').replace(/  <!-- APP-MODULES:BEGIN[\s\S]*?APP-MODULES:END -->/, '').replace(/ 'sha256-[^']+'/g, ''));
const version = hash.digest('hex').slice(0, 10);

// ------------------------------------------------------------------ index.html
const modules = files.filter((f) => f.endsWith('.js') && f !== 'js/boot.js');
const v = (f) => `${f}?v=${version}`;
const importMap = JSON.stringify({ imports: Object.fromEntries(modules.map((f) => [`./${f}`, `./${v(f)}`])) });
const cspHash = `'sha256-${createHash('sha256').update(importMap).digest('base64')}'`;
const preload = ['js/app.js', 'js/ui.js', 'js/store.js', 'js/content.js', 'js/course.js', 'js/views/shared.js', 'js/views/onboarding.js', 'js/views/home.js', 'js/views/about.js'];
const block = [
  '  <!-- APP-MODULES:BEGIN (generated by tools/build-sw.mjs; do not edit) -->',
  `  <script type="importmap">${importMap}</script>`,
  '  <link rel="preload" href="content/course.json" as="fetch" crossorigin="anonymous">',
  ...preload.map((f) => `  <link rel="modulepreload" href="${v(f)}">`),
  `  <script type="module" src="${v('js/app.js')}"></script>`,
  '  <!-- APP-MODULES:END -->',
].join('\n');
const indexPath = join(WEB, 'index.html');
let html = readFileSync(indexPath, 'utf8');
if (!html.includes('APP-MODULES:BEGIN')) {
  // First run: replace the hand-written preload/module block.
  html = html.replace(/  <!-- Flatten the module waterfall[\s\S]*?<script type="module" src="js\/app\.js"><\/script>/, '  <!-- APP-MODULES:BEGIN -->\n  <!-- APP-MODULES:END -->');
}
html = html.replace(/  <!-- APP-MODULES:BEGIN[\s\S]*?APP-MODULES:END -->/, block);
const setCsp = (s) => s.replace(/script-src 'self'( 'sha256-[^']+')?/, `script-src 'self' ${cspHash}`);
html = setCsp(html);
writeFileSync(indexPath, html);
const headersPath = join(WEB, '_headers');
if (existsSync(headersPath)) writeFileSync(headersPath, setCsp(readFileSync(headersPath, 'utf8')));

// ------------------------------------------------------------------ service-worker manifest
// Modules are precached under their versioned URL (what pages request) and their plain URL
// (what older browsers without import maps request).
const shell = ['./', 'index.html', ...files.flatMap((f) => (modules.includes(f) ? [v(f), f] : [f]))];
const bytes = files.reduce((s, f) => s + statSync(join(WEB, f)).size, 0);
writeFileSync(join(WEB, 'sw-manifest.js'), `// Generated by tools/build-sw.mjs — do not edit.\nself.__GCM = ${JSON.stringify({ version, shell }, null, 1)};\n`);
console.log(`version ${version}: ${files.length} shell files (${(bytes / 1024).toFixed(0)} KB), ${modules.length} versioned modules`);
